{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <1110pyte.TestClass object at 0x03BE0B10>\n\n    def test_two(self):\n        x = 'hello'\n>       assert hasattr(x,'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\n1110pyte.py:18: AssertionError"}, "start": 1636688901942, "stop": 1636688901943, "uuid": "6cff210b-7be2-4cb5-a2a9-61b4f65efcb0", "historyId": "baeeb25867bcb9812fdf010befb60366", "testCaseId": "0c0719fb698352f5053bb3a8f8f857d8", "fullName": "1110pyte.TestClass#test_two", "labels": [{"name": "suite", "value": "1110pyte"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "WIN-A65OPQJS5PB"}, {"name": "thread", "value": "5484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "1110pyte"}]}